"""empty message

Revision ID: 26cc75c08fc0
Revises: d4107637e7b2
Create Date: 2025-05-21 03:49:28.187012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26cc75c08fc0'
down_revision = 'd4107637e7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('current_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
